name: Deploy Godot Web Export

on:
  push:
    branches:
      - main  # Change if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true  # Make sure to download Git LFS files

      - name: Fetch LFS files
        run: git lfs pull

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: .  # Uploads the whole repository, including .pck

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
